# Generated by Django 5.2.11 on 2026-02-24 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='seller_attr_slug_24fceb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='seller.attribute')),
            ],
            options={
                'ordering': ['attribute', 'display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(blank=True, help_text='Auto-generated: BRD-XXXXXX format', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Actual selling price; must be <= MRP', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current available stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='seller.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='CDN-hosted image URL')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.productvariant')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_amount', models.IntegerField(help_text='Positive = restock / return. Negative = purchase / damage.')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Customer Purchase'), ('RETURN', 'Customer Return'), ('RESTOCK', 'Manual Restock'), ('ADJUSTMENT', 'Manual Adjustment'), ('DAMAGE', 'Damaged / Lost'), ('CANCELLED', 'Order Cancelled')], max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='Optional: order number or adjustment ID', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='seller.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('store_slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('gst_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Store bio/description shown to customers')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.sellerprofile'),
        ),
        migrations.CreateModel(
            name='VariantAttributeBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='seller.attributeoption')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='seller.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='attributeoption',
            index=models.Index(fields=['attribute', 'value'], name='seller_attr_attribu_c0b307_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'value')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku_code'], name='seller_prod_sku_cod_437a57_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='seller_prod_product_d72fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['selling_price'], name='seller_prod_selling_3f9b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock_quantity'], name='seller_prod_stock_q_14d479_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['variant', 'is_primary'], name='seller_prod_variant_a24509_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant', 'reason'], name='seller_inve_variant_d6b6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant', '-created_at'], name='seller_inve_variant_9df876_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['store_slug'], name='seller_sell_store_s_f81622_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified', 'verification_status'], name='seller_sell_is_veri_38db58_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='seller_prod_slug_57edeb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'is_active'], name='seller_prod_seller__230f66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='seller_prod_brand_0e8254_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='seller_prod_subcate_0abcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattributebridge',
            index=models.Index(fields=['variant', 'option'], name='seller_vari_variant_3612a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributebridge',
            unique_together={('variant', 'option')},
        ),
    ]
