# Generated by Django 5.2.11 on 2026-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_reviewreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
