# Generated by Django 5.2.11 on 2026-03-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_productgallery_video_and_optional_image'),
        ('seller', '0018_delete_commission'),
    ]

    operations = [
    ]
