# Generated by Django 5.2.11 on 2026-02-24 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscountBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfferBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('coupon_type', models.CharField(choices=[('SINGLE_USE', 'Single Use Per User'), ('MULTI_USE', 'Multi Use'), ('ONE_TIME', 'One Time Total')], default='MULTI_USE', max_length=20)),
                ('usage_limit', models.IntegerField(default=1, help_text='Max total redemptions (0 = unlimited)')),
                ('used_count', models.IntegerField(default=0)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to apply coupon', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. '10% Off', 'Flat ₹200 Off'", max_length=100)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FLAT', 'Flat Amount (₹)')], db_index=True, default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or flat amount in ₹', max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value to apply this discount', max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer'), ('SITE_WIDE', 'Site-Wide Offer')], db_index=True, default='PRODUCT', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offer_banners/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferDiscountBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate (%) applied at time of sale', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Actual ₹ commission charged on this order item', max_digits=10)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SETTLED', 'Settled'), ('DISPUTED', 'Disputed'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscountBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOfferBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
