# Generated by Django 5.2.11 on 2026-02-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bnadmin', '0001_initial'),
        ('core', '0001_initial'),
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='core.category'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='core.category'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'discount_type'], name='bnadmin_dis_is_acti_6ca4aa_idx'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount rule this coupon activates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='bnadmin.discount'),
        ),
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='bnadmin.discount'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['slug'], name='bnadmin_off_slug_d5b91f_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'offer_type'], name='bnadmin_off_is_acti_af0dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['start_date', 'end_date'], name='bnadmin_off_start_d_0e1d33_idx'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='bnadmin.offer'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_discounts', to='bnadmin.discount'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_discounts', to='bnadmin.offer'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='customer.orderitem'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='bnadmin.discount'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='seller.product'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='bnadmin.offer'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='seller.product'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='bnadmin_cou_code_81f35b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='bnadmin_cou_start_d_46caea_idx'),
        ),
        migrations.AddIndex(
            model_name='categorydiscountbridge',
            index=models.Index(fields=['category', 'discount'], name='bnadmin_cat_categor_adf288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorydiscountbridge',
            unique_together={('category', 'discount')},
        ),
        migrations.AddIndex(
            model_name='categoryofferbridge',
            index=models.Index(fields=['category', 'offer'], name='bnadmin_cat_categor_a68dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryofferbridge',
            unique_together={('category', 'offer')},
        ),
        migrations.AddIndex(
            model_name='offerdiscountbridge',
            index=models.Index(fields=['offer', 'discount'], name='bnadmin_off_offer_i_cb36b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerdiscountbridge',
            unique_together={('offer', 'discount')},
        ),
        migrations.AddIndex(
            model_name='platformcommission',
            index=models.Index(fields=['seller', 'settlement_status'], name='bnadmin_pla_seller__614de9_idx'),
        ),
        migrations.AddIndex(
            model_name='platformcommission',
            index=models.Index(fields=['settlement_status', '-created_at'], name='bnadmin_pla_settlem_df1325_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscountbridge',
            index=models.Index(fields=['product', 'discount'], name='bnadmin_pro_product_204b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productdiscountbridge',
            unique_together={('product', 'discount')},
        ),
        migrations.AddIndex(
            model_name='productofferbridge',
            index=models.Index(fields=['product', 'offer'], name='bnadmin_pro_product_29e0cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productofferbridge',
            unique_together={('product', 'offer')},
        ),
    ]
